name: test_flutter
description: Info Page Made With Flutter

publish_to: 'github'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - Assets/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/font1.ttf
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico.ttf
    - family: SourceSans
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf